# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.4'

    - name: Build for Windows x64
      run: |
        GOOS=windows GOARCH=amd64 go build -o myapp.exe .
      
    - name: Upload Windows Binary
      uses: actions/upload-artifact@v4.6.0
      with:
        name: myapp-windows
        path: myapp.exe

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.8
          
